### ISSUE TITLE
Would this project be possible to solder using a soldering iron

### ISSUE THREAD

**Issue by h4z-dev** [arwidcool/Solder-Plate#6]
I'm starting to learn electronics and have a soldering iron and am decent with tht components and was wondering the viability of hand soldering the SMD components?
:)

**Comment by vactomas** [comment]
Hey, I haven't made this project yet, but quickly going through the BOM I see 0603 or 0805 package size components which can be hand soldered. I made a keyboard and soldered many 0603 diodes and it was fine. If you are not sure, you can always buy SMD soldering kit to try it out

**Comment by arwidcool** [comment]
Yes, its possible, totally! easy? no. The atmega is tricky to solder.  There is also a problem with the layout of the right hand connector I need to fix, but havent had time.
